server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:credits
    driverClassName: org.h2.Driver
    username: dev
    password: developer
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  session:
    store-type: redis
redis:
  server: localhost
  port: 6379

# API properties
rules:
  cash-balance-ratio: 0.333333333333333     #Risk management rule based on cash balance, 3:1 ratio
  monthly-revenue-ratio: 0.2                #Risk management rule based on monthly revenue, 5:1 ratio
  retry-interval: 30000                     #Time interval allowed for the next request once it has been rejected
  tolerated-rejections: 3                   #Maximum number of rejections before return falling message: "A sales agent will contact you"
  max-accepted-requests: 3                  #Maximum number of requests allowed once it has been accepted
  max-accepted-requests-interval: 120000    #Time interval allowed for requests once it has been accepted